#!/usr/bin/env python3
"""
Generate a calibrated GCAISPACESHIPGLOBALS.GLOBAL.EXML from your game's vanilla values.

The two calibrated variants keep the freighter's own retaliation for deliberate attacks; they only
change how the alert counter reacts to sparse, accidental hits. Because they are expressed relative
to the vanilla numbers, you must feed those in, either from the raw .MBIN (extract it from
PCBANKS/NMSARC.*.pak with AMUMSS, NMSPE or PSArcTool) or by hand from an MBINCompiler dump.

    python3 tools/make_variant.py --mode strict  --mbin path/to/GCAISPACESHIPGLOBALS.GLOBAL.MBIN
    python3 tools/make_variant.py --mode forgive --attack-threshold 3 --alert-threshold 1 --timeout-rate 0.1

Modes
  strict   Raise both alert thresholds by --threshold-mult (default 5x). The counter behaves exactly
           as in vanilla otherwise: slow decay, hostility persists like vanilla. Stray hits over a
           whole battle must now add up to 5x the vanilla budget before the hangar closes; a
           sustained attack on a cargo pod still gets there quickly. Safest for publishing.
  forgive  Keep vanilla thresholds but make the counter drain a full bar in --drain-seconds
           (default 15 s), starting --min-time seconds (default 2 s) after the last hit. Sparse
           hits never accumulate; continuous fire still trips hostility within a second or two;
           the freighter forgives you shortly after you stop. More lenient, but an attacker can
           dock again ~15 s after a raid, so the deterrent is only the pods' own sentinel and
           standing penalties plus turret fire during the raid.
  both     strict thresholds AND forgive-style decay.

Writes GLOBALS/GCAISPACESHIPGLOBALS.GLOBAL.EXML under --out (default: variants/E-Calibrated/GAMEDATA/MODS/FreighterFriendlyFireCalibrated).
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from read_globals import load_fields  # noqa: E402

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!--
  FreighterFriendlyFireCalibrated (mode: {mode})
  Generated by tools/make_variant.py from vanilla values:
    FreighterAlertThreshold        = {v_alert}
    FreighterAttackAlertThreshold  = {v_attack}
    FreighterAlertTimeOutMinTime   = {v_min}
    FreighterAlertTimeOutRate      = {v_rate}
  Partial patch for GLOBALS/GCAISPACESHIPGLOBALS.GLOBAL.MBIN. Only the listed properties change.
-->
<Data template="cGcAISpaceshipGlobals">
{props}
</Data>
"""


def fmt(x):
    return f"{float(x):.6f}"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--mode", choices=["strict", "forgive", "both"], required=True)
    ap.add_argument("--mbin", help="vanilla GCAISPACESHIPGLOBALS.GLOBAL.MBIN to read the base values from")
    ap.add_argument("--alert-threshold", type=float, help="vanilla FreighterAlertThreshold (if no --mbin)")
    ap.add_argument("--attack-threshold", type=float, help="vanilla FreighterAttackAlertThreshold (if no --mbin)")
    ap.add_argument("--timeout-rate", type=float, help="vanilla FreighterAlertTimeOutRate (if no --mbin)")
    ap.add_argument("--timeout-min-time", type=float, help="vanilla FreighterAlertTimeOutMinTime (if no --mbin)")
    ap.add_argument("--threshold-mult", type=float, default=5.0, help="strict/both: multiply both thresholds by this")
    ap.add_argument("--drain-seconds", type=float, default=15.0, help="forgive/both: seconds to drain a full attack bar")
    ap.add_argument("--min-time", type=float, default=2.0, help="forgive/both: seconds after the last hit before decay starts")
    ap.add_argument("--out", default="variants/E-Calibrated/GAMEDATA/MODS/FreighterFriendlyFireCalibrated")
    a = ap.parse_args()

    if a.mbin:
        v = load_fields(a.mbin)
    else:
        v = {
            "FreighterAlertThreshold": a.alert_threshold,
            "FreighterAttackAlertThreshold": a.attack_threshold,
            "FreighterAlertTimeOutRate": a.timeout_rate,
            "FreighterAlertTimeOutMinTime": a.timeout_min_time,
        }
    missing = [k for k in ("FreighterAlertThreshold", "FreighterAttackAlertThreshold") if v.get(k) is None]
    if a.mode in ("forgive", "both") and v.get("FreighterAttackAlertThreshold") is None:
        missing.append("FreighterAttackAlertThreshold")
    if missing:
        sys.exit("missing vanilla values: " + ", ".join(sorted(set(missing))) + " (pass --mbin or the --*-threshold flags)")
    if v["FreighterAttackAlertThreshold"] <= 0:
        sys.exit("vanilla FreighterAttackAlertThreshold is 0 or negative; another mod (e.g. 'Pissed Off Freighters') has already overridden it. Read the untouched file.")

    props = []
    if a.mode in ("strict", "both"):
        props.append(("FreighterAlertThreshold", v["FreighterAlertThreshold"] * a.threshold_mult))
        props.append(("FreighterAttackAlertThreshold", v["FreighterAttackAlertThreshold"] * a.threshold_mult))
    if a.mode in ("forgive", "both"):
        attack = v["FreighterAttackAlertThreshold"] * (a.threshold_mult if a.mode == "both" else 1.0)
        props.append(("FreighterAlertTimeOutMinTime", a.min_time))
        props.append(("FreighterAlertTimeOutRate", attack / a.drain_seconds))

    body = "\n".join(f'\t<Property name="{n}" value="{fmt(x)}" />' for n, x in props)
    xml = TEMPLATE.format(mode=a.mode, props=body,
                          v_alert=v.get("FreighterAlertThreshold"), v_attack=v.get("FreighterAttackAlertThreshold"),
                          v_min=v.get("FreighterAlertTimeOutMinTime"), v_rate=v.get("FreighterAlertTimeOutRate"))
    out_dir = os.path.join(a.out, "GLOBALS")
    os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, "GCAISPACESHIPGLOBALS.GLOBAL.EXML")
    open(out, "w", encoding="utf-8").write(xml)
    print(f"wrote {out}")
    for n, x in props:
        print(f"  {n:<32} = {fmt(x)}")


if __name__ == "__main__":
    main()
